name: build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11 ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Java ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        ORG_GRADLE_PROJECT_ossrhUsername: xxx
        ORG_GRADLE_PROJECT_ossrhPassword: xxx
      run: ./gradlew check
